version: "2.1"

services:

##########
# SONARR #
##########
  sonarr:
    image: linuxserver/sonarr
    container_name: htpc-sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/sonarr:/config
      - ${SERIES_PATH}/:/tv
      - ${DOCUS_PATH}/:/docus
      - ${DOWNLOAD_PATH}/:/downloads
    ports:
      - ${SONARR_PORT}:8989
    expose:
      - ${SONARR_PORT}
    restart: ${RESTART_POLICY}
    labels:
      - ${UPDATE_ON}

##########
# RADARR #
##########
  radarr:
    image: linuxserver/radarr
    container_name: htpc-radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/radarr:/config
      - ${MOVIES_PATH}/:/movies
      - ${DOCUS_PATH}/:/docus
      - ${DOWNLOAD_PATH}/:/downloads
    ports:
      - ${RADARR_PORT}:7878
    expose:
      - ${RADARR_PORT}
    restart: ${RESTART_POLICY}
    labels:
      - ${UPDATE_ON}

############
# PROWLARR #
############
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: htpc-prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/prowlarr:/config
    ports:
      - ${PROWLARR_PORT}:9696
    expose:
      - ${PROWLARR_PORT}
    restart: ${RESTART_POLICY}
    labels:
      - ${UPDATE_ON}

##########
# BYPARR #
##########
  byparr:
    image: ghcr.io/thephaseless/byparr:latest
    container_name: htpc-byparr
    environment:
      - LOG_LEVEL=INFO
    ports:
      - "8191:8191"
    restart: ${RESTART_POLICY}

###############
# QBITTORRENT #
###############
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: htpc-qbit
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${QBIT_GUI}
      - TORRENTING_PORT=${QBIT_PORT}
    volumes:
      - ${CONFIG_PATH}/qbit/appdata:/config
      - ${DOWNLOAD_PATH}:/downloads #optional
    ports:
      - ${QBIT_GUI}:8080
      - ${QBIT_PORT}:6881
      - ${QBIT_PORT}:6881/udp
    stop_grace_period: "10s" #optional
    restart: ${RESTART_POLICY}
    labels:
      - ${UPDATE_ON}

##########
# BAZARR #
##########
  bazarr:
    image: linuxserver/bazarr
    container_name: htpc-bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/bazarr:/config
      - ${SERIES_PATH}/:/tv
      - ${MOVIES_PATH}/:/movies
    ports:
      - ${BAZARR_PORT}:6767
    expose:
      - ${BAZARR_PORT}
    restart: ${RESTART_POLICY}
    labels:
      - ${UPDATE_ON}

##############
# YOUTUBE-DL #
##############
  youtube:
    image: kmb32123/youtube-dl-server
    container_name: htpc-youtube-dl
    volumes:
      - ${YOUTUBE_PATH}/:/youtube-dl
    ports:
      - ${YOUTUBE_PORT}:8080
    expose:
      - ${YOUTUBE_PORT}
    restart: ${RESTART_POLICY}
    labels:
      - ${UPDATE_ON}

###########
# READARR #
###########
  readarr:
    container_name: htpc-readarr
    image: hotio/readarr:nightly
    restart: ${RESTART_POLICY}
    ports:
      - "${READARR_PORT}:8787"
    expose:
      - ${READARR_PORT}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=002
      - TZ=${TZ}
      - ARGS
    volumes:
      - ${CONFIG_PATH}/readarr:/config
      - ${BOOKS_PATH}/:/books
    labels:
      - ${UPDATE_ON}

########
# OMBI #
########
  ombi:
    image: linuxserver/ombi
    container_name: htpc-ombi
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/ombi:/config
    ports:
      - ${OMBI_PORT}:3579
    expose:
      - ${OMBI_PORT}
    restart: ${RESTART_POLICY}
    labels:
      - ${UPDATE_ON}
